[build]
  base = "sites/www"
  command = "nx run www:build"
  functions = "sites/www/netlify/functions"
  publish = "sites/www/public"

#[build.environment]
  #NODE_VERSION = "18.7.0"

#[dev]
  #command = "npm start"
