#[build]
 # base = "sites/www"
 # command = "eleventy"
 # functions = "sites/www/netlify/functions"
 # publish = "public"

#[build.environment]
  #NODE_VERSION = "18.7.0"

#[dev]
  #command = "npm start"
